- alias: Cold for sleep
  hide_entity: False
  trigger:
    platform: time
    after: '1:01:00'
  action:
  - service: climate.set_temperature
    data:
      temperature: 64

- alias: Thermostat temperature extreme
  hide_entity: False
  trigger:
    platform: numeric_state
    entity_id: climate.thermostat
    value_template: '{ state.attributes.temperature }'
    above: 80
    below: 60
  action:
  - service: notify.local_smtp
    data:
      title: 'Thermostat set below 60 or above 80  degrees fahrenheit!'
      message: 'The Honeywell thermostat is set below 60 or above 80 degrees fahrenheit'
