- alias: 'Sunset lights'
  hide_entity: false
  trigger:
    platform: sun
    event: sunset
    offset: "-00:45:00"
  action:
  # 45 minutes before sunset turn on lights to dim level
  - service: light.turn_on
    entity_id: light.downstairs_hallway_light
    data:
      brightness: 130
  - delay: 00:30:00
  # 30 minutes later brighten some
  - service: light.turn_on
    entity_id: light.downstairs_hallway_light
    data:
      brightness: 180
  - delay: 00:15:00
  # 15 minutes later brighten fully
  - service: light.turn_on
    entity_id: light.downstairs_hallway_light
    data:
      brightness: 255

- alias: 'Sleep lights'
  hide_entity: false
  trigger:
    platform: time
    after: '1:01:00'
  action:
  - service: light.turn_off
    entity_id: light.downstairs_hallway_light

- alias: 'Sunrise lights'
  hide_entity: false
  trigger:
    platform: sun
    event: sunrise
  action:
  - service: light.turn_on
    entity_id: light.downstairs_hallway_light
    data:
      brightness: 100
